### ISSUE TITLE
Small note, but good job updating the addon.

### ISSUE THREAD

**Issue by nimids** [Ranoth/Loot-A-Rang-Matic-Reforged#1]
One small potential issue, I see is you name your addon "ThisAddon" when you set up the AceAddon object If another person also did that it would make a conflict.

Otherwise, Thanks for updating this I've been asked by a few people to update it.

**Comment by Ranoth** [comment]
Thanks for pointing this out, I just fixed it.
>Fixed in [release v1.1.3](https://github.com/Ranoth/Loot-A-Rang-Matic-Reforged/releases/tag/v1.1.3)
